version: '3.8'

services:
  backend:
    build: ./backend
    container_name: radio-backend-prod
    ports:
      - "4004:5000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: radio-frontend-prod
    ports:
      - "3004:3000"
    restart: always
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - NODE_ENV=production
