worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    resolver 127.0.0.11 valid=30s;

    server {
        listen 5001;
        listen 5002;
        listen 5003;
        listen 5004;
        listen 5005;
        listen 5006;

        location / {
            lua_need_request_body on;

            access_by_lua_block {
    local http = require "resty.http"
    local cjson = require "cjson"
    local hc = http.new()

    local port = ngx.var.server_port
    local prob_id = tonumber(port) - 5000

    local req_body = ngx.req.get_body_data()
    local headers = ngx.req.get_headers()
    local user_id = "cmmezvpdn0002q4qggqvlyf0l"

    ngx.log(ngx.ERR, "req_body: ", tostring(req_body))
    ngx.log(ngx.ERR, "headers: ", cjson.encode(headers))

    local res, err = hc:request_uri("http://host.docker.internal:4000/api/collect", {
        method = "POST",
        body = cjson.encode({
            user_id    = user_id,
            problem_id = prob_id,
            method     = ngx.req.get_method(),
            uri        = ngx.var.request_uri,
            headers    = headers,
            payload    = req_body or ""
        }),
        headers = { ["Content-Type"] = "application/json" }
    })

    if not res then
        ngx.log(ngx.ERR, "Failed to send log: ", err)
    end
}

            proxy_pass http://host.docker.internal:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

