server {
  listen 80;

  location /img/ {
    alias /srv/prob6-img/;
  }

  location /api/ {
    proxy_pass http://prob6-backend:5000/;
  }

  location /auth/ {
    proxy_pass http://prob6-backend:5000/auth/;
  }

  location /admin {
    proxy_pass http://prob6-backend:5000/admin;
    proxy_set_header Authorization $http_authorization;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}
